// Code generated by protoc-gen-go. DO NOT EDIT.
// source: random-service/random-service.proto

package random_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RandomParams struct {
	Max                  int64    `protobuf:"varint,1,opt,name=Max,proto3" json:"Max,omitempty"`
	Min                  int64    `protobuf:"varint,2,opt,name=Min,proto3" json:"Min,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomParams) Reset()         { *m = RandomParams{} }
func (m *RandomParams) String() string { return proto.CompactTextString(m) }
func (*RandomParams) ProtoMessage()    {}
func (*RandomParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbaab0d8183f2ca3, []int{0}
}

func (m *RandomParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomParams.Unmarshal(m, b)
}
func (m *RandomParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomParams.Marshal(b, m, deterministic)
}
func (m *RandomParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomParams.Merge(m, src)
}
func (m *RandomParams) XXX_Size() int {
	return xxx_messageInfo_RandomParams.Size(m)
}
func (m *RandomParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomParams.DiscardUnknown(m)
}

var xxx_messageInfo_RandomParams proto.InternalMessageInfo

func (m *RandomParams) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *RandomParams) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

type RandomInt struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomInt) Reset()         { *m = RandomInt{} }
func (m *RandomInt) String() string { return proto.CompactTextString(m) }
func (*RandomInt) ProtoMessage()    {}
func (*RandomInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbaab0d8183f2ca3, []int{1}
}

func (m *RandomInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomInt.Unmarshal(m, b)
}
func (m *RandomInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomInt.Marshal(b, m, deterministic)
}
func (m *RandomInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomInt.Merge(m, src)
}
func (m *RandomInt) XXX_Size() int {
	return xxx_messageInfo_RandomInt.Size(m)
}
func (m *RandomInt) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomInt.DiscardUnknown(m)
}

var xxx_messageInfo_RandomInt proto.InternalMessageInfo

func (m *RandomInt) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DateTime struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateTime) Reset()         { *m = DateTime{} }
func (m *DateTime) String() string { return proto.CompactTextString(m) }
func (*DateTime) ProtoMessage()    {}
func (*DateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbaab0d8183f2ca3, []int{2}
}

func (m *DateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTime.Unmarshal(m, b)
}
func (m *DateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTime.Marshal(b, m, deterministic)
}
func (m *DateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTime.Merge(m, src)
}
func (m *DateTime) XXX_Size() int {
	return xxx_messageInfo_DateTime.Size(m)
}
func (m *DateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTime.DiscardUnknown(m)
}

var xxx_messageInfo_DateTime proto.InternalMessageInfo

func (m *DateTime) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestDateTime struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestDateTime) Reset()         { *m = RequestDateTime{} }
func (m *RequestDateTime) String() string { return proto.CompactTextString(m) }
func (*RequestDateTime) ProtoMessage()    {}
func (*RequestDateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbaab0d8183f2ca3, []int{3}
}

func (m *RequestDateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestDateTime.Unmarshal(m, b)
}
func (m *RequestDateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestDateTime.Marshal(b, m, deterministic)
}
func (m *RequestDateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestDateTime.Merge(m, src)
}
func (m *RequestDateTime) XXX_Size() int {
	return xxx_messageInfo_RequestDateTime.Size(m)
}
func (m *RequestDateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestDateTime.DiscardUnknown(m)
}

var xxx_messageInfo_RequestDateTime proto.InternalMessageInfo

func (m *RequestDateTime) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestPass struct {
	Seed                 int64    `protobuf:"varint,1,opt,name=Seed,proto3" json:"Seed,omitempty"`
	Length               int64    `protobuf:"varint,2,opt,name=Length,proto3" json:"Length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPass) Reset()         { *m = RequestPass{} }
func (m *RequestPass) String() string { return proto.CompactTextString(m) }
func (*RequestPass) ProtoMessage()    {}
func (*RequestPass) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbaab0d8183f2ca3, []int{4}
}

func (m *RequestPass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPass.Unmarshal(m, b)
}
func (m *RequestPass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPass.Marshal(b, m, deterministic)
}
func (m *RequestPass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPass.Merge(m, src)
}
func (m *RequestPass) XXX_Size() int {
	return xxx_messageInfo_RequestPass.Size(m)
}
func (m *RequestPass) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPass.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPass proto.InternalMessageInfo

func (m *RequestPass) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *RequestPass) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type RandomPass struct {
	Password             string   `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomPass) Reset()         { *m = RandomPass{} }
func (m *RandomPass) String() string { return proto.CompactTextString(m) }
func (*RandomPass) ProtoMessage()    {}
func (*RandomPass) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbaab0d8183f2ca3, []int{5}
}

func (m *RandomPass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomPass.Unmarshal(m, b)
}
func (m *RandomPass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomPass.Marshal(b, m, deterministic)
}
func (m *RandomPass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomPass.Merge(m, src)
}
func (m *RandomPass) XXX_Size() int {
	return xxx_messageInfo_RandomPass.Size(m)
}
func (m *RandomPass) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomPass.DiscardUnknown(m)
}

var xxx_messageInfo_RandomPass proto.InternalMessageInfo

func (m *RandomPass) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*RandomParams)(nil), "passsquale.grpc.random_service.RandomParams")
	proto.RegisterType((*RandomInt)(nil), "passsquale.grpc.random_service.RandomInt")
	proto.RegisterType((*DateTime)(nil), "passsquale.grpc.random_service.DateTime")
	proto.RegisterType((*RequestDateTime)(nil), "passsquale.grpc.random_service.RequestDateTime")
	proto.RegisterType((*RequestPass)(nil), "passsquale.grpc.random_service.RequestPass")
	proto.RegisterType((*RandomPass)(nil), "passsquale.grpc.random_service.RandomPass")
}

func init() {
	proto.RegisterFile("random-service/random-service.proto", fileDescriptor_cbaab0d8183f2ca3)
}

var fileDescriptor_cbaab0d8183f2ca3 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0xab, 0xb5, 0x19, 0x15, 0x65, 0x11, 0x29, 0x39, 0x48, 0x9b, 0x1e, 0x8c, 0xff,
	0x52, 0xa8, 0x27, 0xf1, 0x26, 0x42, 0x11, 0x14, 0x4a, 0x14, 0x0f, 0x5e, 0x64, 0x6d, 0x86, 0x34,
	0xd8, 0x6c, 0xd2, 0x9d, 0x8d, 0xfa, 0xe9, 0xfc, 0x6c, 0x92, 0xcd, 0x36, 0x18, 0x0f, 0x26, 0xa7,
	0xec, 0x1b, 0x7e, 0x8f, 0xc9, 0x7b, 0x0c, 0x8c, 0x24, 0x17, 0x41, 0x12, 0x5f, 0x10, 0xca, 0x8f,
	0x68, 0x8e, 0xe3, 0xaa, 0xf4, 0x52, 0x99, 0xa8, 0x84, 0x1d, 0xa5, 0x9c, 0x88, 0x56, 0x19, 0x5f,
	0xa2, 0x17, 0xca, 0x74, 0xee, 0x15, 0xd4, 0xab, 0xa1, 0x9c, 0x09, 0xec, 0xf8, 0x7a, 0x32, 0xe3,
	0x92, 0xc7, 0xc4, 0xf6, 0xa1, 0xf3, 0xc0, 0xbf, 0xfa, 0xad, 0x41, 0xcb, 0xed, 0xf8, 0xf9, 0x53,
	0x4f, 0x22, 0xd1, 0x6f, 0x9b, 0x49, 0x24, 0x9c, 0x21, 0x58, 0x85, 0xe7, 0x4e, 0x28, 0x76, 0x00,
	0x9b, 0xcf, 0x7c, 0x99, 0xa1, 0xb1, 0x14, 0xc2, 0x19, 0x40, 0xef, 0x96, 0x2b, 0x7c, 0x8a, 0x62,
	0xac, 0x12, 0xd6, 0x9a, 0x38, 0x86, 0x3d, 0x1f, 0x57, 0x19, 0x92, 0xaa, 0x01, 0xaf, 0x60, 0xdb,
	0x80, 0x33, 0x4e, 0xc4, 0x18, 0x6c, 0x3c, 0x22, 0x06, 0x66, 0x9d, 0x7e, 0xb3, 0x43, 0xe8, 0xde,
	0xa3, 0x08, 0xd5, 0xc2, 0xfc, 0xa5, 0x51, 0x8e, 0x0b, 0xb0, 0x0e, 0x47, 0xc4, 0x6c, 0xe8, 0xe5,
	0xdf, 0xcf, 0x44, 0x06, 0x66, 0x43, 0xa9, 0x27, 0xdf, 0x6d, 0xe8, 0x16, 0x28, 0x0b, 0xc0, 0x9a,
	0xa2, 0x32, 0xe2, 0xdc, 0xfb, 0xbf, 0x3f, 0xef, 0x77, 0x79, 0xf6, 0x49, 0x33, 0x3a, 0xaf, 0x2d,
	0x80, 0xad, 0x29, 0xea, 0xe8, 0x6c, 0x5c, 0xeb, 0xaa, 0xf6, 0x64, 0xbb, 0x75, 0x86, 0xb2, 0xd1,
	0x05, 0xec, 0x96, 0x59, 0x74, 0x07, 0x67, 0x0d, 0x77, 0xe5, 0xb0, 0x7d, 0xda, 0x34, 0x3c, 0xd1,
	0xcd, 0xe8, 0x65, 0x98, 0xbe, 0x87, 0x7f, 0x6e, 0xf0, 0xba, 0xca, 0xbf, 0x75, 0xf5, 0x4d, 0x5e,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x9f, 0x0c, 0xe0, 0xba, 0x02, 0x00, 0x00,
}
